### ISSUE TITLE
Write a few sentences about uniform PRNG initialization

### ISSUE THREAD

**Issue by 0u812** [0u812/ieee-reproducibility-paper#2]

**Comment by jonrkarr** [comment]
Added a couple sentences about this. Please review to see if this captures your thoughts.

**Comment by 0u812** [comment]
I rewrote the paragraph to better reflect my thoughts. I mainly just want to draw attention to the fact that subtle points like initialization can be handled differently by different implementations, and that developers shouldn't assume they're portable. If I add too many specific details, I'll have to include my code for the Python vs C++ example, which I think is overkill.
